### ISSUE TITLE
Error when running JuliaNFC on Ubuntu 22.04 (something about glibc 2.36)

### ISSUE THREAD

**Issue by JornJorn** [Inter-Actief/JulianaNFC_Python#11]
Your north eastern neighbors have some issues with running JuliaNFC. We get the following error.

![image](https://github.com/user-attachments/assets/8e853c80-3fd7-40a0-bee4-98457b86ce01)

**Comment by Kurocon** [comment]
It seems Ubuntu 22.04 has a slightly older version of [glibc (2.35)](https://launchpad.net/ubuntu/jammy/+source/glibc) than what the JulianaNFC release executable was built with (2.36), so it can't start.

Ubuntu 24.04 does have a higher glibc version (2.39), so if an upgrade is possible it should work on the newer Ubuntu version.
Otherwise, I can see if I can rebuild the executable for Ubuntu 22.04 soon, but I will need to setup a VM for that.

If you don't mind some manual work, you can also use [option 2 from the readme](https://github.com/Inter-Actief/JulianaNFC_Python?tab=readme-ov-file#juliananfc---optie-2) to install, which will run it directly from the source code with python.

Let me know what your preferred solution is.

**Comment by JornJorn** [comment]
Thanks for the quick reply. Upgrading to 24.04 works fine for us.
Met vriendelijke groet,

Jorn de Jong

**Comment by Kurocon** [comment]
OK, good luck with the upgrade. Let us know if you get any more problems!
